import { HardHat } from "lucide-react";
import { Eyebrow } from "@/components/app/eyebrow";

export type DocParty = { label: string; lines: (string | null | undefined)[] };
export type DocMeta = { label: string; value: React.ReactNode };

/**
 * Print-ready document sheet (PO / invoice / RFQ). Letterhead + parties + body.
 * Monochrome and print-safe; the only accent is a thin brand rule at the top.
 */
export function DocumentSheet({
  company,
  docType,
  number,
  meta = [],
  parties = [],
  children,
  footer,
}: {
  company: { name: string; address?: string | null; country?: string | null };
  docType: string;
  number: string;
  meta?: DocMeta[];
  parties?: DocParty[];
  children: React.ReactNode;
  footer?: React.ReactNode;
}) {
  return (
    <div className="print-sheet mx-auto my-6 w-full max-w-[820px] rounded-lg border bg-card p-10 shadow-sm print:my-0">
      <div className="mb-8 h-1 w-full rounded-full bg-brand" />

      <header className="flex items-start justify-between gap-6">
        <div className="flex items-start gap-3">
          <div className="flex size-9 items-center justify-center rounded-md bg-foreground text-background">
            <HardHat className="size-5" strokeWidth={2.25} />
          </div>
          <div>
            <p className="font-display text-lg font-semibold tracking-tight text-foreground">
              {company.name}
            </p>
            {company.address && (
              <p className="max-w-xs text-xs leading-relaxed text-muted-foreground">
                {company.address}
              </p>
            )}
            {company.country && (
              <p className="text-xs text-muted-foreground">{company.country}</p>
            )}
          </div>
        </div>
        <div className="text-right">
          <Eyebrow className="block text-muted-foreground">{docType}</Eyebrow>
          <p className="font-display text-2xl font-semibold tracking-tight text-foreground tabular">
            {number}
          </p>
        </div>
      </header>

      {(parties.length > 0 || meta.length > 0) && (
        <div className="mt-8 flex flex-wrap justify-between gap-6 border-t pt-6">
          <div className="flex flex-wrap gap-x-12 gap-y-4">
            {parties.map((p) => (
              <div key={p.label}>
                <Eyebrow className="mb-1.5 block text-muted-foreground">
                  {p.label}
                </Eyebrow>
                {p.lines
                  .filter(Boolean)
                  .map((line, i) => (
                    <p
                      key={i}
                      className={
                        i === 0
                          ? "text-sm font-medium text-foreground"
                          : "text-xs text-muted-foreground"
                      }
                    >
                      {line}
                    </p>
                  ))}
              </div>
            ))}
          </div>
          {meta.length > 0 && (
            <dl className="space-y-1.5 text-right">
              {meta.map((m) => (
                <div key={m.label} className="flex justify-end gap-4 text-sm">
                  <dt className="eyebrow self-center text-muted-foreground">
                    {m.label}
                  </dt>
                  <dd className="min-w-24 font-medium text-foreground tabular">
                    {m.value}
                  </dd>
                </div>
              ))}
            </dl>
          )}
        </div>
      )}

      <div className="mt-8">{children}</div>

      {footer && (
        <footer className="mt-10 border-t pt-6 text-xs leading-relaxed text-muted-foreground">
          {footer}
        </footer>
      )}

      <p className="mt-8 text-center text-[0.625rem] uppercase tracking-[0.18em] text-muted-foreground/70">
        Generated by ConstructFlow
      </p>
    </div>
  );
}
